# Generated by Django 3.1.2 on 2021-01-12 16:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='コースID')),
                ('course_name', models.CharField(max_length=255, verbose_name='コース名')),
                ('depart_id', models.CharField(max_length=10, verbose_name='学科ID')),
            ],
        ),
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('depart_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='学科ID')),
                ('depart_name', models.CharField(max_length=255, verbose_name='学科名')),
            ],
        ),
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_id', models.CharField(max_length=10)),
                ('enrolled_status', models.CharField(max_length=2)),
                ('enrolled_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('poster_id', models.AutoField(primary_key=True, serialize=False, verbose_name='投稿ID')),
                ('poster_name', models.CharField(blank=True, max_length=20, verbose_name='投稿者')),
                ('poster_content', models.CharField(blank=True, max_length=250, verbose_name='投稿内容')),
                ('post_data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changefile', models.FileField(upload_to='')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_number', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='学籍番号')),
                ('student_name', models.CharField(max_length=20, verbose_name='氏名')),
                ('class_number', models.CharField(max_length=6, verbose_name='クラス番号')),
                ('couse_id', models.CharField(max_length=10, null=True, verbose_name='コースID')),
                ('enrolled_id', models.CharField(max_length=10, verbose_name='在籍ID')),
                ('secret_key', models.CharField(blank=True, default='a', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.CharField(blank=True, max_length=7, primary_key=True, serialize=False, verbose_name='科目番号')),
                ('subject_name', models.CharField(max_length=25, verbose_name='科目名')),
                ('units', models.CharField(max_length=2, verbose_name='単位数')),
                ('dividend_period', models.CharField(max_length=8, verbose_name='配当期')),
                ('lecture_name', models.CharField(default='', max_length=25, verbose_name='担当者')),
            ],
        ),
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(default='', max_length=255, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=255)),
                ('admin_flag', models.IntegerField(default=0)),
                ('secret_key', models.CharField(blank=True, default='a', max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False, verbose_name='成績ID')),
                ('evaluation', models.CharField(blank=True, max_length=2, verbose_name='評価')),
                ('student_number', models.CharField(blank=True, max_length=5, verbose_name='学籍番号')),
                ('subject_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GradeInquiry.subject', verbose_name='科目番号')),
            ],
        ),
    ]
