# Generated by Django 3.1.2 on 2021-01-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradeInquiry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='secret_key',
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='secret_key',
            field=models.IntegerField(default=0),
        ),
    ]
