# Generated by Django 3.1.2 on 2020-10-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradeInquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='username',
            field=models.CharField(default='', editable=False, max_length=255, unique=True),
        ),
    ]
