# Generated by Django 3.1.2 on 2020-10-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradeInquiry', '0002_auto_20201020_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
