# Generated by Django 3.1.2 on 2020-10-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradeInquiry', '0005_auto_20201020_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('depart_id', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('depart_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('depart_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_id', models.IntegerField(max_length=10)),
                ('enrolled_status', models.CharField(max_length=2)),
                ('enrolled_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('subject_id', models.CharField(max_length=7)),
                ('student_number', models.CharField(max_length=5)),
                ('evaluation', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_number', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=20)),
                ('class_number', models.CharField(max_length=6)),
                ('enrolled_id', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=25)),
                ('dividend_period', models.CharField(max_length=8)),
                ('units', models.IntegerField(max_length=2)),
            ],
        ),
    ]
