# Generated by Django 3.1.2 on 2020-10-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradeInquiry', '0007_auto_20201022_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='couse_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
