# Generated by Django 3.1.2 on 2020-10-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradeInquiry', '0008_student_couse_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birthday',
            field=models.DateTimeField(null=True),
        ),
    ]
