# Generated by Django 3.1.2 on 2020-11-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradeInquiry', '0009_student_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='admin_flag',
            field=models.IntegerField(default=0),
        ),
    ]
