# Generated by Django 3.1.3 on 2020-12-01 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GradeInquiry', '0011_auto_20201119_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='evaluation',
            field=models.CharField(blank=True, max_length=2, verbose_name='評価'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GradeInquiry.subject', verbose_name='科目番号'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_id',
            field=models.CharField(blank=True, max_length=7, primary_key=True, serialize=False),
        ),
    ]
