# Generated by Django 3.1.3 on 2020-12-01 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GradeInquiry', '0012_auto_20201201_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='subject_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='GradeInquiry.subject', verbose_name='科目番号'),
        ),
    ]
